;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	c-electric-brace
	c-electric-paren
	c-electric-pound
	c-electric-semi&comma
	c-electric-slash
	cua--prefix-override-handler
	cua-exchange-point-and-mark
	cua-paste
	mouse-set-region
	previous-buffer
	sgml-slash
	))

(setq mc/cmds-to-run-once
      '(
	comment-region
	electric-pair-delete-pair
	ido-find-file
	next-buffer
	overwrite-mode
	))
